import { useNavigate } from 'react-router';
import { useAuth } from '../contexts/AuthContext';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { ArrowLeft, Download } from 'lucide-react';

export default function ReportCardPage() {
  const navigate = useNavigate();
  const { user } = useAuth();

  const handleDownload = () => {
    // Simulate download
    alert('Report card downloaded successfully!');
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={() => navigate('/home')}>
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex items-center gap-3">
              <Download className="w-8 h-8 text-indigo-600" />
              <h1 className="text-2xl font-semibold text-gray-900">Report Card</h1>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Card>
          <CardHeader className="text-center border-b pb-6">
            <div className="mb-4">
              <h2 className="text-2xl font-bold">Student Report Card</h2>
              <p className="text-gray-600 mt-2">Academic Year 2025-2026</p>
            </div>
            <div className="grid grid-cols-2 gap-4 text-left mt-6">
              <div>
                <p className="text-sm text-gray-600">Student Name</p>
                <p className="font-semibold">{user?.name}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Student ID</p>
                <p className="font-semibold">{user?.studentId}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Class</p>
                <p className="font-semibold">{user?.class}-{user?.section}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Course</p>
                <p className="font-semibold">{user?.course}</p>
              </div>
            </div>
          </CardHeader>
          <CardContent className="pt-6">
            <div className="space-y-6">
              <div>
                <h3 className="font-semibold mb-3">Academic Performance</h3>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <p className="text-center text-gray-600 mb-2">Overall GPA</p>
                  <p className="text-4xl font-bold text-center text-indigo-600">3.78</p>
                </div>
              </div>

              <div>
                <h3 className="font-semibold mb-3">Attendance</h3>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <p className="text-center text-gray-600 mb-2">Overall Attendance</p>
                  <p className="text-4xl font-bold text-center text-green-600">86%</p>
                </div>
              </div>

              <div className="pt-4 border-t">
                <Button onClick={handleDownload} className="w-full" size="lg">
                  <Download className="w-5 h-5 mr-2" />
                  Download Complete Report Card (PDF)
                </Button>
              </div>

              <p className="text-xs text-center text-gray-500">
                This is an official document generated by the Student Management System
              </p>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
